version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: ["make", "dev"]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://adm:123@db:5432/tulltaxan

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tulltaxan
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   ports:
  #     - "5050:80" # Maps pgAdmin's web interface to localhost:5050
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   depends_on:
  #     - db


volumes:
  db_data:
